version: '3'

services:
        backend:
                build: .
                command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
                container_name: hamzar
                volumes:
                        - .:/hamzar
                ports:
                        - "8000:8000"
                depends_on:
                        - database
        frontend:
                build: ./frontend/
                container_name: frontend
                ports:
                        - "3000:80"

        database:
                image: "postgres"
                container_name: "db_postgres"
                ports:
                        - "5432:5432"
                volumes:
                        - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
                restart: "always"
                environment:
                        - POSTGRES_USER=hamzar
                        - POSTGRES_PASSWORD=0214
                        - POSTGRES_DB=hamzar
